version: "3.7"
services:
  node:
    build: .
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./public
        target: /app/public
    depends_on:
      - db
      - redis
    networks:
      - webnet
    environment:
      - NODE_ENV=production
      - PORT=80
      - COOKIE_SECRET=COOKIE
      - SEQUELIZE_PASSWORD=password
      - SEQUELIZE_USERNAME=root
      - SEQUELIZE_DATABASE=booking
      - SEQUELIZE_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  db:
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/mysql
    networks:
      - webnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:5.0.9-alpine
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"
    networks:
      - webnet
    restart: always
    command: redis-server
networks:
  webnet:
    driver: bridge
volumes:
  redis:
